### ISSUE TITLE
GradedTraversable.traverse stack-traces in unchecked_cast

### ISSUE THREAD

**Issue by Release-Candidate** [stephentetley/graded-lib#1]
If I understand the stack trace correctly, this `unchecked_cast` fails: https://github.com/stephentetley/graded-lib/blob/master/src/GradedTraversable.flix#L46 when using `GradedTraversable.traverse`.

Stack trace:
```
 FAIL  test4
    java.lang.ClassCastException: class Parser$Parser$Obj$Obj$Obj cannot be cast to class IParser$Char$Obj$Obj (Parser$Parser$Obj$Obj$Obj and IParser$Char$Obj$Obj are in unnamed module of loader ca.uwaterloo.flix.language.phase.jvm.FlixClassLoader @1ad8df52)
        at Clo$traverse$157471.invoke(Unknown Source)
        at Cont$Obj.unwind(Cont$Obj)
        at Def$test4.invoke(Unknown Source)
        at Cont$Bool.unwind(Cont$Bool)
        at Ns.m_test4(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:298)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledDefs$2(JvmBackend.scala:271)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.runTest(Tester.scala:182)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.$anonfun$run$7(Tester.scala:153)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.$anonfun$run$7$adapted(Tester.scala:152)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.run(Tester.scala:152)
```
Sources of test4: https://github.com/Release-Candidate/flix-test/blob/main/src/FlixParse.flix#L143
You can use this small test project to reproduce the error, if needed.

**Comment by stephentetley** [comment]
Hi - thanks for the bug report, I'll look into it today.

**Comment by stephentetley** [comment]
I think the problem is that FlixParse's `point` (and also `empty`) are `Pure` rather than being effect polymorphic.

The cast in the GradedApplicative instance was then causing the runtime cast failure.

It's a bit unintuitive that `point` should be polymorphic in its effect rather than pure. I've made that mistake myself - it is still present in the functions `empty` and `singleton` in my revision of Iterator in Flix's stdlib. I didn't realized Iterator was a graded monad when I wrote it and some effects "float" to the right hand side of the type signatures when they should be captured in the Iterator type constructor. I've hesitated from updating Iterator in the stdlib because at the moment I don't know if Iterator should be a graded monad or an effect handler and you can't currently define effect handlers in Flix code (they have to defined in the compiler).

These modications should clear the runtime cast failure:

~~~


mod Parser {
    pub def empty(): Parser[i, ef, a] =
        Parser.Parser(_ -> checked_ecast(Err(Error.Empty)))

    pub def point(x: a): Parser[i, ef, a] =
        Parser.Parser(input -> checked_ecast(Ok(x, input)))
        
...

instance GradedApplicative[Parser[i]] {

    pub def point(x: a): Parser[i, ef, a] =
        Parser.point(x)

...

~~~

**Comment by Release-Candidate** [comment]
Thanks for your help, that was the problem. 
Yes, I wouldn't have thought that moving the cast from the `GradedApplicative.point` to `Parser.point` would solve the issue.
I also thought that at least one of the `point` function would show up on the stack trace.

**Comment by stephentetley** [comment]
Thanks - Flix's stack trace is a bit funny for locating cast errors. It will show you something is wrong, but because more often that not it will be in the code of a higher order function it doesn't always point you to the error itself.

By the way, I've just made a new release of `graded-lib` but it might need a compiler built from the Flix repo's "head" rather than the last release (0.35.0).

**Comment by Release-Candidate** [comment]
`graded-lib` 0.3.1 works for me with Flix 0.35.

As you are working on the PR of the Graded* type classes, do you know if there is going to be for notation support for `GradedApplicator` and `-Monad`?

**Comment by stephentetley** [comment]
Hopefully there will be syntax support for graded monads at some point, though it really depends on what form effects take when they are fully integrated and users can define their own effects / handlers.

My feeling is that Flix will still need graded monads as they provide a way to sequence operations using effects and I think at the implementation level sequencing will need to be in CPS to avoid stack overflows as Flix is strict. A graded Codensity / CPS monad can provide stack safe sequencing and I don't think you could have CPS as an effect. It might be that the Flix standard libraries end up having one graded CPS monad and many effects.

At the moment without special syntax I use the "explicit bind" style that was sometimes used in Haskell:

https://github.com/stephentetley/flix-basicdb/blob/fc51065ff75e73eb3a01eb2e0348ccec5782e2e9/src/BasicDb/Reader.flix#L27
